// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppLink: typeof import('./components/AppLink.vue')['default']
    DarkToggle: typeof import('./components/DarkToggle.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Post: typeof import('./components/Post.vue')['default']
    PostList: typeof import('./components/PostList.vue')['default']
    PostsList: typeof import('./components/PostsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubNav: typeof import('./components/SubNav.vue')['default']
  }
}
